/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Sistemas_login.utilitarios;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author User
 */
public class Tela_principal extends javax.swing.JFrame {

    /**
     * Creates new form Tela_principal
     */
    public Tela_principal() {
   
        
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension d = tk.getScreenSize();
        
        this.setBounds(0, 0, d.width, d.height);
         utilitarios u = new utilitarios();
        u.inserirIcone(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        funcionario = new javax.swing.JMenuItem();
        cliente = new javax.swing.JMenuItem();
        estado = new javax.swing.JMenuItem();
        cidade = new javax.swing.JMenuItem();
        bairro = new javax.swing.JMenuItem();
        rua = new javax.swing.JMenuItem();
        telefone = new javax.swing.JMenuItem();
        tipo_telefone = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        produto = new javax.swing.JMenuItem();
        marca = new javax.swing.JMenuItem();
        tipo = new javax.swing.JMenuItem();
        venda = new javax.swing.JMenuItem();
        itemvendas1 = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        Sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(448, 340));
        setMinimumSize(new java.awt.Dimension(448, 340));
        setPreferredSize(new java.awt.Dimension(448, 340));
        setSize(new java.awt.Dimension(448, 340));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new javax.swing.OverlayLayout(jPanel1));
        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/11195823-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu-suspenso.png"))); // NOI18N
        jMenu3.setText("Menu");

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addition.png"))); // NOI18N
        jMenu1.setText("Cadastros");

        funcionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        funcionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eu-iria.png"))); // NOI18N
        funcionario.setText("funcionario");
        funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionarioActionPerformed(evt);
            }
        });
        jMenu1.add(funcionario);

        cliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clientes.png"))); // NOI18N
        cliente.setText("cliente");
        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });
        jMenu1.add(cliente);

        estado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        estado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/estados-unidos.png"))); // NOI18N
        estado.setText("Estado");
        estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoActionPerformed(evt);
            }
        });
        jMenu1.add(estado);

        cidade.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        cidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cidade.png"))); // NOI18N
        cidade.setText("cidade");
        cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidadeActionPerformed(evt);
            }
        });
        jMenu1.add(cidade);

        bairro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        bairro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cidade-verde.png"))); // NOI18N
        bairro.setText("bairro");
        bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bairroActionPerformed(evt);
            }
        });
        jMenu1.add(bairro);

        rua.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        rua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rua.png"))); // NOI18N
        rua.setText("rua");
        rua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruaActionPerformed(evt);
            }
        });
        jMenu1.add(rua);

        telefone.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        telefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/telefones.png"))); // NOI18N
        telefone.setText("telefone");
        telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneActionPerformed(evt);
            }
        });
        jMenu1.add(telefone);

        tipo_telefone.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        tipo_telefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/responsivo.png"))); // NOI18N
        tipo_telefone.setText("Tipo telefone");
        tipo_telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo_telefoneActionPerformed(evt);
            }
        });
        jMenu1.add(tipo_telefone);

        jMenu3.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/adicionar-produto.png"))); // NOI18N
        jMenu2.setText("Produtos");

        produto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        produto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/adicionar-produto.png"))); // NOI18N
        produto.setText("produto");
        produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoActionPerformed(evt);
            }
        });
        jMenu2.add(produto);

        marca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        marca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-square-brackets-32.png"))); // NOI18N
        marca.setText("marca");
        marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaActionPerformed(evt);
            }
        });
        jMenu2.add(marca);

        tipo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        tipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu-suspenso.png"))); // NOI18N
        tipo.setText("tipo");
        tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoActionPerformed(evt);
            }
        });
        jMenu2.add(tipo);

        venda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        venda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/crescimento.png"))); // NOI18N
        venda.setText("venda");
        venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendaActionPerformed(evt);
            }
        });
        jMenu2.add(venda);

        itemvendas1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itemvendas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-finalizar-pedido-32.png"))); // NOI18N
        itemvendas1.setText("itemvenda");
        itemvendas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemvendas1ActionPerformed(evt);
            }
        });
        jMenu2.add(itemvendas1);

        jMenu3.add(jMenu2);

        exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_BACK_SPACE, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-exit-64.png"))); // NOI18N
        exit.setText("deslogar");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu3.add(exit);

        Sair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_END, java.awt.event.InputEvent.SHIFT_MASK));
        Sair.setText("Exit");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        jMenu3.add(Sair);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 464, 315);
    }// </editor-fold>//GEN-END:initComponents

    private void funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionarioActionPerformed
        // TODO add your handling code here:
        tela_funcionario SEUFRAME = new  tela_funcionario();
        SEUFRAME.setVisible(true);
       
    }//GEN-LAST:event_funcionarioActionPerformed

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed
        // TODO add your handling code here:
        tela_Cliente SEUFRAME1 = new  tela_Cliente();
        SEUFRAME1.setVisible(true);
       
    }//GEN-LAST:event_clienteActionPerformed

    private void cidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadeActionPerformed
        cidade cidade = new  cidade();
        cidade.setVisible(true);
    }//GEN-LAST:event_cidadeActionPerformed

    private void bairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bairroActionPerformed
        // TODO add your handling code here:
     Bairros Bairro = new Bairros();
        Bairro.setVisible(true);
     
    }//GEN-LAST:event_bairroActionPerformed

    private void vendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendaActionPerformed
        // TODO add your handling code here:
        venda vendas = new venda();
       vendas.setVisible(true);
    }//GEN-LAST:event_vendaActionPerformed

    private void telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneActionPerformed
        // TODO add your handling code here:
        tela_telefone tef = new tela_telefone();
        tef.setVisible(true);
    }//GEN-LAST:event_telefoneActionPerformed

    private void estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoActionPerformed
        // TODO add your handling code here:
        estado es = new estado();
        es.setVisible(true);
       
    }//GEN-LAST:event_estadoActionPerformed

    private void produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoActionPerformed
        // TODO add your handling code here:
        Produto es1 = new Produto();
        es1.setVisible(true);
    }//GEN-LAST:event_produtoActionPerformed

    private void ruaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruaActionPerformed
        // TODO add your handling code here:
        rua ruas = new rua();
        ruas.setVisible(true);
    }//GEN-LAST:event_ruaActionPerformed

    private void tipo_telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo_telefoneActionPerformed
        // TODO add your handling code here:
        tela_tipotelefone tef1 = new tela_tipotelefone();
        tef1.setVisible(true);
    }//GEN-LAST:event_tipo_telefoneActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
       UsuarioLoginVIEW exits = new UsuarioLoginVIEW();
        exits.setVisible(true);
              this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaActionPerformed
        // TODO add your handling code here:
        marca mar = new marca();
        mar.setVisible(true);
    }//GEN-LAST:event_marcaActionPerformed

    private void tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoActionPerformed
        // TODO add your handling code here:
       tipo tipos = new tipo();
       tipos.setVisible(true);
    }//GEN-LAST:event_tipoActionPerformed

    private void itemvendas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemvendas1ActionPerformed
        // TODO add your handling code here:
        itemvenda itemv = new itemvenda();
       itemv.setVisible(true);
    }//GEN-LAST:event_itemvendas1ActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // TODO add your handling code here:
        System.exit(EXIT_ON_CLOSE);
    }//GEN-LAST:event_SairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Sair;
    private javax.swing.JMenuItem bairro;
    private javax.swing.JMenuItem cidade;
    private javax.swing.JMenuItem cliente;
    private javax.swing.JMenuItem estado;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenuItem funcionario;
    private javax.swing.JMenuItem itemvendas1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem marca;
    private javax.swing.JMenuItem produto;
    private javax.swing.JMenuItem rua;
    private javax.swing.JMenuItem telefone;
    private javax.swing.JMenuItem tipo;
    private javax.swing.JMenuItem tipo_telefone;
    private javax.swing.JMenuItem venda;
    // End of variables declaration//GEN-END:variables

    public void limpar() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
